### ISSUE TITLE
Tag a New Release

### ISSUE THREAD

**Issue by haneefmubarak** [rescrv/HyperLevelDB#22]
@rescrv seeing as there hasn't been any recent activity on the repo, would you mind tagging a release on the latest usable commit you feel is appropriate?

As to why this is important, please have a look at the recent discussion in basho/leveldb#229.

Thanks!

**Comment by rescrv** [comment]
Given that there isn't activity on the project and that I haven't looked at it for awhile, I'm not comfortable tagging a release.  To my mind, the tag of a release would signal an improvement in quality and performance and should also come with caveats about possible regressions.  I'm not in a place to enumerate those.

If there is someone who wants to take maintainership of the project and tag a release, I would be able to make myself available in my free time to answer a (small amount of) questions to facilitate that.

Otherwise, you can feel pretty comfortable depending on whatever revision you already depend upon as it's not likely to change soon.
